"""init

Revision ID: 39d620a21674
Revises: 
Create Date: 2025-04-27 16:35:03.138086

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '39d620a21674'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_letter_templates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('subject', sa.String(length=100), nullable=False),
                    sa.Column('params', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('role_name', sa.String(length=10), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('role_name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=40), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('hashed_pwd', sa.String(length=255), nullable=False),
                    sa.Column('avatar', sa.String(length=255), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.Date(), nullable=False),
                    sa.Column('updated_at', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('auth_sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('refresh_token', sa.String(), nullable=False),
                    sa.Column('device_type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.Date(), nullable=False),
                    sa.Column('expires_at', sa.Date(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('refresh_token')
                    )
    op.create_table('followers',
                    sa.Column('follower_id', sa.Integer(), nullable=False),
                    sa.Column('followed_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
                    )
    op.create_table('sent_mail_letters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('template_id', sa.Integer(), nullable=False),
                    sa.Column('send_at', sa.DateTime(), nullable=False),
                    sa.Column('opened', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['template_id'], ['mail_letter_templates.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute("INSERT INTO roles (id, role_name) VALUES (1, 'admin')")
    op.execute("INSERT INTO roles (id, role_name) VALUES (2, 'moderator')")
    op.execute("INSERT INTO roles (id, role_name) VALUES (3, 'user')")

    op.execute(
        f"INSERT INTO mail_letter_templates (id, name, subject, created_at) VALUES (1, 'draft', 'draft', NOW())")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_mail_letters')
    op.drop_table('followers')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('mail_letter_templates')
    # ### end Alembic commands ###
