"""add qr code to content model

Revision ID: 40550ec471e7
Revises: 7a626c5bb5d5
Create Date: 2025-05-15 17:44:56.476376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40550ec471e7'
down_revision: Union[str, None] = '7a626c5bb5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('image', sa.String(length=255), nullable=False))
    op.add_column('contents', sa.Column('qr_code', sa.String(length=255), nullable=True))
    op.drop_column('contents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('contents', 'qr_code')
    op.drop_column('contents', 'image')
    # ### end Alembic commands ###
