"""update comments model

Revision ID: 413e23d14a82
Revises: ab3f80f74b17
Create Date: 2025-05-16 12:26:15.331727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413e23d14a82'
down_revision: Union[str, None] = 'ab3f80f74b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=500), nullable=False))
    op.add_column('comments', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['reply_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'reply_id')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
