ACCOUNT_EXIST = "Account already exists"
CONTACT_ID_NOT_FOUND = "Contact with this ID not found in your's contact book"
VERIFICATION_ERROR = "Verification error"
USER_NOT_FOUNDED_BY_EMAIL = "Not exist user with that email"
INVALID_EMAIL = "Invalid email"
EMAIL_NOT_CONFIRMED = "Email isn't confirmed yet"
INVALID_PASSWORD = "Invalid password"
INVALID_TOKEN = "Invalid refresh token"
INCORRECT_DB_CONFIGURATION = "Database is not configured correctly"
DB_CONNECTION_ERROR = "Error connecting to the database"
TAG_ALREADY_EXIST = "This tag already used for this contact"
INVALID_VERIFICATION_TOKEN = "Invalid token for email verification"
EXPIRED_TOKEN = "Token has expired"
INVALID_TOKEN_SCOPE = "Invalid scope for token"
BAD_CREDENTIALS = "Could not validate credentials"
FORBIDDEN = "You don't have permission to access this resource"
DRAFT_LETTER_NOT_FOUND = "Draft letter not found"
PASSWORD_NOT_MATCH = "Password doesn't match"
EMAIL_TAG_NOT_FOUND = "Email with given tag not found for this contact"
PHONE_TAG_NOT_FOUND = "Phone with given tag not found for this contact"

POST_NOT_FOUND = "Post not found"
COMMENT_NOT_FOUND = "Comment not found"

THIS_USER_NOT_FOLLOWED = "You don't follow this user"
THIS_USER_NOT_FOLLOWED_YOU = "This user don't follow you"
YOU_CANT_FOLLOW_YOURSELF = "You can't follow yourself"
YOU_ALREADY_FOLLOW_THIS_USER = "You already follow this user"